spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/forum
    username: forum_microservice_user
    password: forum_microservice_password
  flyway:
    locations: [ classpath:db/migration, classpath:db/testdata ]
