server:
    port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anime
    username: anime_microservice_user
    password: anime_microservice_password
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
