spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user_microservice_user
    password: user_microservice_password
  flyway:
    locations: [ classpath:db/migration, classpath:db/testdata ]
