name: Anime Service

on:
    workflow_dispatch:
    push:
        paths:
            - "*.gradle"
            - "service/Anime_Service/**"
            - "service/common/**"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

            - name: Build the App
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :Anime_Service:build -x test
                  build-root-directory: .
                  gradle-executable: ./gradlew

    test:
        runs-on: ubuntu-latest
        name: Tests
        needs: build

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

            - name: Test the App
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :Anime_Service:test --scan
                  build-root-directory: .
                  gradle-executable: ./gradlew

            - name: Save report if error
              if: ${{ failure() }}
              uses: actions/upload-artifact@v3
              with:
                  name: test-report
                  path: .service/Anime_Service/build/reports/tests
