name: Frontend

on:
    workflow_dispatch:
    push:
        paths:
            - "*.gradle"
            - "service/Frontend/**"
            - "service/common/API_Generation/**"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build

        steps:
            - name: Set up JDK 21 for
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'adopt'

            - name: Set up node
              uses: actions/setup-node@v3
              with:
                  node-version: '18.17.1'

            - uses: actions/checkout@v3

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: See all tasks
              run: ./gradlew tasks --all


            -   name: See Frotnend dependencies
                run: ./gradlew :Frontend:buildEnvironment --stacktrace

            -   name: Build the Service
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: :Frontend:build -x test --stacktrace
                    gradle-executable: ./gradlew

    test:
        runs-on: ubuntu-latest
        name: Tests
        needs: build

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 21 for
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'adopt'

            - name: Set up node
              uses: actions/setup-node@v3
              with:
                node-version: '18.17.1'

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Test Frontend
              run: ./gradlew :Frontend:test
