name: User Service

on:
    workflow_dispatch:
    push:
        paths:
            - "*.gradle"
            - "service/User_Service/**"
            - "service/common/**"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'adopt'

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Build the Service
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :User_Service:build -x test
                  gradle-executable: ./gradlew

    test:
        runs-on: ubuntu-latest
        name: Tests
        needs: build

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'adopt'

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Test the Service
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :User_Service:test --scan
                  gradle-executable: ./gradlew

            - name: Save report if error
              if: ${{ failure() }}
              uses: actions/upload-artifact@v3
              with:
                  name: test-report
                  path: ./service/User_Service/build/reports/tests
